### ISSUE TITLE
Can write_jmv corrupt the file?

### ISSUE THREAD

**Issue by MAgojam** [sjentsch/jmvReadWrite#2] opened 2021-08-11 15:51 UTC
OS: Win10 Pro (ITA)
Jamovi: 2.0.0
R: 4.1.0
RStudio: 1.4.1717
jmvReadWrite: 0.2.0

Hi, Sebastian.
I installed **jmvReadWrite** and tried with this simple code:
```
remotes::install_github("sjentsch/jmvReadWrite", force = TRUE)
library(jmvReadWrite)

data = read_jmv(fleNme = "D:/Temp/exp_1.omv")
write_jmv(dtaFrm = data, fleNme = "D:/Temp/dup_exp_1.omv")
```
The file (dup_exp_1.omv) generated with the write_jmv function is not loaded by jamovi which releases the error:
_Unable to open
File is corrupt (manifest is corrupt)_

I'm doing it wrong?
Where can I look?

If it helps, I am attaching the two omv files.
[Temp.zip](https://github.com/sjentsch/jmvReadWrite/files/6969696/Temp.zip)

Thanks and a good greeting.
Maurizio

**Comment by sjentsch** [comment] 2021-08-12 07:55
There is likely a change in file format in connection with the changes with jamovi 1.8 (save variables, e.g., residuals) and 2.0 (I have to figure out what changes were made). That, I am afraid, will need a deeper look in the Python-code that jamovi uses to read in omv-files. I will do it as soon as I can, but it might unfortunately take a bit of time.

**Comment by MAgojam** [comment] 2021-08-13 12:41
Thanks, Sebastian.
I will continue to follow you and will also go to take a look at the Python code.

Cheers,
Maurizio

**Comment by sjentsch** [comment] 2021-08-15 15:00
The error should be fixed now (at least, the file now opens on my machine). Please report back if you still experience issues.

I also used the chance to improve the README... ;-)

Please close the issue once you confirmed that is working on your machine too.

**Comment by MAgojam** [comment] 2021-08-15 19:41
Hi, Sebastian.
You were faster than light.

Unfortunately, on my machine, the update to #v0.2.1 (08/15/2021) did not fix.

However, I have some remarks about the contents of the file that might help.
I changed the extension of the file, saved with **jmv_vrite**, from .omv to .zip and I could verify that the **META-inf** folder with its **Manifest.mf** file was missing.
I created Manifest.mf folder and file, renamed from .zip to .omv and it was possible to open it with jamovi v2.0.0 without error messages.
I also saw that jamovi, by saving the .omv file, inserts this in **meta** and in **Manifest.fm**
`jamovi-Archive-Version: 11.0`

Thanks for your attention and the time you spent.

Cheers,
Maurizio

**Comment by sjentsch** [comment] 2021-08-16 04:50
I actually removed that intentionally since I - after speaking to Jonathon - assumed it wouldn't be necessary any longer (for a transition period, jamovi should accept either META-INF/MANIFEST.MF and meta and after that transition to meta only). I will ask Jonathon to chase up why it is working in Linux but not in Windows.
For now, I put creating META-INF/MANIFEST.MF back in the write_jmv-function. I can remove it in a later version if it breaks things now.
Regarding the jamovi-Archive-Version: I would like to keep it at 9.0 for the moment. I did not implement saving variables (implemented in 10.0) and whatever changes happened with 2.0 (version 11.0) yet. I therefore believe that 9.0 might be saver for now. If 9.0 is not working for you let me know, then I will think how to best proceed.

**Comment by sjentsch** [comment] 2021-08-16 05:26
BTW: I changed read_jmv to read_omv and write_jmv to write_omv (since that's the actual file extension). Sorry for the fuss.

**Comment by MAgojam** [comment] 2021-08-17 19:25
Hi, Sebastian.

I took some time to dig deeper thanks to your suggestions.
You're right, you don't need **META-INF/MANIFEST.MF** too, just the **meta** file.
The problem is at the level of the writeLine function that in Linux the default EOL is (LF) "\n", but in Windows a (CR) is added so as to be (CRLF) "\r \n".
So that the 109 bytes, **meta** file goes to 113 bytes.
Jamovi in ​​opening the .omv file wants to find (LF) for the **meta** file EOL, but finding (CRLF), releases the error message "Unable to open, File is corrupt (manifest is corrupt)".
This is a possible reason why it works on Linux, but not Windows.
I took the liberty of making a few small changes to your code that generates the **meta** file (_sort of Win2Unix_) to have only (LF) as EOL in the file, this:
```
# create meta, write it and add it to ZIP file
    mnfTxt <- c("Manifest-Version: 1.0", 
                "Data-Archive-Version: 1.0.2", 
                "jamovi-Archive-Version: 9.0", 
                paste("Created-By: jmvReadWrite", 
                      utils::packageVersion("jmvReadWrite")))
    con <- file("meta", open="wb")
    writeLines(mnfTxt, con, sep="\n")
    close(con)
    utils::zip(fleNme, 'meta', flags = "-r9Xq")
    unlink('meta')
    rm("mnfTxt")
```
So it works for me also under Windows and at the moment the various files that I have edited and saved with write_omv (with the possibilities of jamovi-Archive-Version: 9.0) are reopened in jamovi, without problems.
Thanks, I continue to keep an eye on your great work.

Cheers,
Maurizio

**Comment by sjentsch** [comment] 2021-08-17 19:41
Thanks for figuring that out, Maurizio!
I will add the sep-parameter for now but I am afraid then it's rather not a problem on my side but on jamovi's. If you look a couple of lines down, there are two other occurrences of me using writeLines (without the sep-parameter) and those are working.
I will speak to Jonathon about that. Generally, the file reading should be system-agnostic - otherwise, one could not open files that were written in Linux or Macs on Windows (or vice versa).

**Comment by sjentsch** [comment] 2021-08-17 19:43
It may take until tomorrow or the day after before I fix that, I am currently working on something else in another branch.

**Comment by sjentsch** [comment] 2021-08-20 17:02
Could you check again whether it is working now? Thank you! S

**Comment by MAgojam** [comment] 2021-08-20 20:21
Hi, Sebastian.

I took a look at jamovi-dev and in particular the **omv.py** file.
I think replace the code at line (296) here:
[https://github.com/jamovi/jamovi/blob/current-dev/server/jamovi/server/formatio/omv.py#L296](url)
with this code:
`regex = r'^jamovi-Archive-Version: ?([0-9]+)\.([0-9]+) ?\r?$'`
can be a solution to keep your code and use it from Linux and Windows.
I created the **omv.pyc** with code modification and replaced in jamovi path, and I have no problem.
What do you say?

Cheers,
Maurizio

**Comment by MAgojam** [comment] 2021-08-20 22:03
I'm back.
I tried now the version you just updated.
It doesn't work and I'll tell you why.

You added '\n' in writeLines(), but connecting to the "meta" file directly in writeLines() opens it in text mode and this in Windows results in a word wrap (CR) in front of the line feed (LF) .
To avoid this, you must first open the "meta" file in binary mode and then make the connection with writeLines(), so as to write only the correct bytes.
I am attaching the working code for the part that concerns the writing of the "meta" file, which is what is checked when opening the file with the script omv.py and generates the error for not intercepting the (CR) in the "Regular Expression Syntax".
For the other writeLines() there are no problems.

```
## create meta, write it and add it to ZIP file ##
## ensure text is UTF-8
mnfTxt <- enc2utf8(c("Manifest-Version: 1.0", 
                     "Data-Archive-Version: 1.0.2", 
                     "jamovi-Archive-Version: 8.0", 
                     paste("Created-By: jmvReadWrite", 
                     utils::packageVersion("jmvReadWrite"))))

## Windows users: It is important to open the file in binary mode, 
## to avoid that in windows the text mode automatically fixes (CRLF) as EOL.
con <- file("meta", open="wb")

## Now with writeLine() we can only have (LF) as EOL
## for the strings inserted in the meta file.
writeLines(mnfTxt, con, sep="\n")
close(con)
utils::zip(fleNme, 'meta', flags = "-r9Xq")
unlink('meta')
rm("mnfTxt")
```

Thanks, Sebastian.
You are doing a great job and if I can contribute, I do it with pleasure.

Cheers,
Maurizio

**Comment by sjentsch** [comment] 2021-08-21 07:04
One last try please!
Afterwards, I will upload the new version to CRAN.

**Comment by MAgojam** [comment] 2021-08-21 12:11
Hi, Sebastian.
Now it also works with Windows.
Tested on various PCs, without error messages!

Thanks and best regards.
Maurizio

**Comment by sjentsch** [comment] 2021-08-23 12:23
Thanks again for your help! I will close the issue now.

jmvReadWrite 0.2.1 should appear soon on CRAN.

**Closed by sjentsch** 2021-08-23 12:23 UTC
